### ISSUE TITLE
Add link to the readable form of tech docs

### ISSUE THREAD

**Issue by mark-cooper** [archivesspace/tech-docs#106]
Suggestion from @quoideneuf during Core Committers meeting:

Tech docs GitHub repo should have link to: https://archivesspace.github.io/tech-docs/ (first line after heading?)

**Comment by trevorthornton** [comment]
@mark-cooper - I added links to both the tech docs site and the repo, each of which will be redundant in one place or the other. 

https://github.com/archivesspace/tech-docs/pull/108

Let me know if you think this will work.
