### ISSUE TITLE
No solr directory in release despite what it says in the docs

### ISSUE THREAD

**Issue by trevorthornton** [archivesspace/tech-docs#125]
@mark-cooper - The revised Solr documentation says:

>> Copy the ArchivesSpace Solr configuration files from the solr directory included with the release into the $SOLR_HOME/server/solr/configsets/archivesspace/conf directory.

But the 3.1.1 release does not seem to include a solr directory. I don't know if this is a documentation issue or build issue.

**Comment by ladyintertect** [comment]
I believe this issue has been resolved in v3.2.0, per this pull request:

https://github.com/archivesspace/archivesspace/pull/2496/commits/82d335bb3f83d538599b3b2dc5278f15b4c685af
