### ISSUE TITLE
Container Management documentation

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/tech-docs#19]
There is a pull request to add documentation to the config-defaults.rb file in the main codebase (https://github.com/archivesspace/archivesspace/pull/1157). Maybe we should beef up the documentation here as well?

**Comment by trevorthornton** [comment]
Yes! We had discussed early on trying to glean some documentation from the comments in the config, and we have a stub page for it here:
https://github.com/archivesspace/tech-docs/blob/master/customization/configuration.md

I'll try to do it when I have time, unless somebody else wants to/is willing to.

**Comment by trevorthornton** [comment]
Took a first pass at converting the documentation from the config file to markdown for tech-docs:
https://github.com/trevorthornton/tech-docs/blob/master/customization/configuration.md

Need to discuss if this format works, and whether or not it's too much of a burden on the developers to keep this file in sync with the in-code documentation in the config

**Comment by trevorthornton** [comment]
I went ahead and merged the config documentation I created a few months ago, which address this issue. Any problems with the documentation can be handled with new issues/pull requests or just fixed by the devs directly.
