### ISSUE TITLE
Incomplete requirements

### ISSUE THREAD

**Issue by LittleMonkeyMojo** [archivesspace/tech-docs#8]
You have tested with Ubuntu Linux and state we need a certain version of Java installed (1.7 or 1.8).  For those of your users who are not all that technically savvy, they will not find "Java 1.7" or "Java 1.8" when they run aptitude or synaptic, or the GUI installer, they will need to install one of the several "jre", "jdk" or "oracle-java" packages.  Sometime after 1.6, Sun (now Oracle) dropped the "1." from the version, while the "default-jre" still has a 1.x version, the actual packages behind that are not. Since you say you've tested with Ubuntu, list the packages which need to be installed.

Also, lower in the "Getting Started" document you state that the user will need "Java version 1.6 (or newer)".  Which is the actual minimum requirement, 1.6 or 1.7?

**Comment by lmcglohon** [comment]
The Getting Started document was updated in the core code repo for v2.3.1. This got moved over with this PR: https://github.com/archivesspace/tech-docs/pull/13.

Still may need to add more information - maybe point to external documentation about Java versions?
